### PR TITLE
redid folder structure for components for easier layout and styling. …

### PR DESCRIPTION
**Pull request by rstootalow**
…Also added Grid component to better leverage Bootstrap responsiveness for frontend

### CODE REVIEW

**Review by scottlehman — APPROVED** [review]
Everything looks good here. approved

**Review by scottlehman — APPROVED** [review]

**Comment by rstootalow** [comment]
Do we know where the conflicts are with the SignUp.js file?

**Comment by scottlehman** [comment]
Not sure yet I'll check it out

**Comment by rstootalow** [comment]
Closing pull request as I found an issue locally that I should be able to fix. Will submit new pull request once fix is in place.

**Pull request closed without merging**
